name: Build Android APK

on:
  push:
    branches: [docker]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up caching for Buildozer dependencies
      - name: Cache Buildozer Environment
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      # Initialize Buildozer (if not already initialized)
      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            pip install buildozer
            buildozer init
          fi

      # Build the APK using Buildozer inside Docker
      - name: Build Android APK (Docker)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/app \
            -v $HOME/.buildozer:/home/user/.buildozer \
            -w /home/user/app \
            ghcr.io/kivy/buildozer \
            bash -c "buildozer android debug"

      # Upload the built APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
