name: CI
on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest  # Change to self-hosted if you need ARM

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Set up Temurin Java 17
      - name: Set up Temurin Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # Install Buildozer and dependencies
      - name: Install Buildozer and dependencies
        run: |
          sudo apt update && sudo apt install -y \
            python3-pip python3-setuptools python3-wheel git zip unzip zlib1g-dev \
            libncurses6 libffi-dev libssl-dev liblzma-dev libgdbm-dev libbz2-dev libreadline-dev \
            libsqlite3-dev libffi-dev libgdbm-compat-dev curl
          python3 -m pip install --upgrade pip setuptools cython
          python3 -m pip install buildozer
      
      # Set up Android SDK and NDK
      - name: Install Android SDK and NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O /tmp/cmdline-tools.zip
          unzip -d ~/.buildozer/android/platform /tmp/cmdline-tools.zip
          rm /tmp/cmdline-tools.zip
          sudo apt-get install aidl 
          yes | ~/.buildozer/android/platform/cmdline-tools/bin/sdkmanager --sdk_root=~/.buildozer/android/platform "platform-tools" "build-tools;33.0.2" "platforms;android-33" "ndk;25.2.9519653"
      
      # Initialize Buildozer (if not already initialized)
      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      # Ensure bin directory exists and copy binary files
      - name: Copy binary files to app's root bin directory
        run: |
          mkdir -p ./bin  # Ensure bin directory exists
          
          # Copy binaries only if they exist and are not already in the bin directory
          for cmd in lscpu ifconfig nproc; do
            if command -v $cmd &>/dev/null && [ ! -f ./bin/$cmd ]; then
              cp $(which $cmd) ./bin/
              chmod +x ./bin/$cmd  # Make it executable
            fi
          done

      # Clean old build to avoid conflicts
      - name: Clean Buildozer build
        run: |
          buildozer android clean
      
      # Build the Android APK
      - name: Build Android APK
        run: |
          buildozer android debug
      
      # Upload the APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
